apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-gitops
    argocd-image-updater.argoproj.io/enable: "true"
  name: app-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gitops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-gitops
    spec:
      containers:
      - image: davidgoncalvesz/images2:app-gitops-13
        name: app-gitops
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-gitops-service
  labels:
    app: app-gitops-service
spec:
  type: NodePort
  ports:
  - nodePort: 30082
    port: 3000
    targetPort: 3000
  selector:
    app: app-gitops
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gitops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app-gitops.92.co.ucll.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-gitops-service
                port:
                  number: 3000
