apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-gitops
  name: app-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-gitops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-gitops
    spec:
      containers:
      - image: davidgoncalvesz/images2:app-gitops-12
        name: app-gitops
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-gitops-service
  labels:
    app: app-gitops-service
spec:
  type: NodePort
  ports:
  - nodePort: 30081
    port: 3000
    targetPort: 3000
  selector:
    app: flaskdemo
