apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-gitops
  labels:
    app: app-gitops
    argocd-image-updater.argoproj.io/enable: "true"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-gitops
  template:
    metadata:
      labels:
        app: app-gitops
    spec:
      containers:
      - name: app-gitops
        image: davidgoncalvesz/images2:app-gitops-17
        resources: {}
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-gitops-service
  labels:
    app: app-gitops-service
spec:
  type: NodePort
  ports:
  - nodePort: 30082
    port: 3000
    targetPort: 3000
  selector:
    app: app-gitops
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gitops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app-gitops.92.co.ucll.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-gitops-service
                port:
                  number: 3000
