apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gitops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host | default "app-gitops.92.co.ucll.cloud" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-gitops-service
                port:
                  number: 3000