apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.labels.app }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: 3000
      targetPort: 3000
  selector:
    app: app-gitops