apiVersion: v1
kind: Service
metadata:
  name: app-gitops-service
  labels:
    app: app-gitops-service
spec:
  type: NodePort
  ports:
  - nodePort: 30082
    port: 3000
    targetPort: 3000
  selector:
    app: app-gitops