apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "app-gitops-service" }}
  labels:
    app: {{ .Values.service.labels.app | default "app-gitops-service" }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
    - nodePort: {{ .Values.service.nodePort | default 30082 }}
      port: {{ .Values.service.port | default 3000 }}
      targetPort: {{ .Values.service.targetPort | default 3000 }}
  selector:
    app: {{ .Values.service.selector.app | default "app-gitops" }}