ingress:
  host: app-gitops-qa.92.co.ucll.cloud

rollout:
  name: app-gitops-qa
  labels:
    app: app-gitops-qa
  replicas: 4
  container:
    name: app-gitops-qa
    image: davidgoncalvesz/app-gitops:qa-28

service:
  name: app-gitops-service-dev
  labels:
    app: app-gitops-service-dev
  nodePort: 30098