ingress:
  host: app-gitops-qa.92.co.ucll.cloud

rollout:
  template:
    spec:
      template:
        spec:
          containers:
            - name: app-gitops
              image: davidgoncalvesz/app-gitops:qa-28

service:
  type: NodePort
  ports:
    - nodePort: 30088
      port: 3000
      targetPort: 3000