ingress:
  host: app-gitops-qa.92.co.ucll.cloud

rollout:
  name: app-gitops-qa
  labels:
    app: app-gitops-qa
  replicas: 4
  container:
    name: app-gitops-qa
    image: davidgoncalvesz/app-gitops:qa-6

service:
  name: app-gitops-service-qa
  labels:
    app: app-gitops-service-qa
  nodePort: 30098

  argocd:
    application:
      annotations:
        argocd-image-updater.argoproj.io/image-list: image=davidgoncalvesz/app-gitops:qa-*
        argocd-image-updater.argoproj.io/image.update-strategy: latest